#!/usr/bin/env bash

## Description: Run phpcbf inside the web container
## Usage: phpcbf [flags] [args]
## Example: "ddev phpcbf" or "ddev phpcbf -n"
## ExecRaw: true

phpcbf -s --report-full --report-summary --report-source src "$@"
