#!/usr/bin/env bash

## Description: Run PHP CS inside the web container
## Usage: phpcs [flags] [args]
## Example: "ddev phpcs" or "ddev phpcs -n"
## ExecRaw: true

phpcs -s --report-full --report-summary --report-source src --ignore=*/.ddev/* "$@"
